apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asshutossh-asshutossh-poi-map-app-dev
  annotations:
    argocd/app-name: asshutossh-asshutossh-poi-map-app-dev
    backstage.io/kubernetes-id: asshutossh-asshutossh-poi-map-app-dev
    backstage.io/kubernetes-namespace: asshutossh
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=asshutossh-asshutossh-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/asshutossh-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/asshutossh/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/asshutossh/deployments/asshutossh-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/asshutossh-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://asshutossh-poi-map-app-asshutossh.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/asshutossh"
  system: workshop-system-asshutossh
  consumesApis:
    - gateway-api-asshutossh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-asshutossh
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/asshutossh"
